# Definição de variáveis (ambiente “local” do REST Client)
@base_url = INSERIR A URL DA SUA PORTA 8080

### Inserir nova pessoa
POST {{ base_url }}/api/pessoas
Content-Type: application/json

{
  "nome": "Gabriel",
  "idade": 28
}

### Listar todas as pessoas
GET {{ base_url }}/api/pessoas
Accept: application/json

### Buscar pessoa por ID
GET {{ base_url }}/api/pessoas/2
Accept: application/json

### Atualizar pessoa (PUT)
PUT {{ base_url }}/api/pessoas/2
Content-Type: application/json

{
  "nome": "Gabriel Marinho",
  "idade": 28
}

### Remover pessoa (DELETE)
DELETE {{ base_url }}/api/pessoas/1
Accept: */*