# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://fantastic-enigma-7vr64vp69j653xg9g-8080.app.github.dev

### Inserir novo produto
POST {{ base_url }}/api/produtos
Content-Type: application/json

{
  "nome": "Notebook",
  "quantidade": 10,
  "valor": 3899.99
}

### Listar todos os produtos
GET {{ base_url }}/api/produtos
Accept: application/json

### Buscar produtos por ID
GET {{ base_url }}/api/produtos/1
Accept: application/json

### Atualizar produto (PUT)
PUT {{ base_url }}/api/produtos/1
Content-Type: application/json

{
  "nome": "Notebook",
  "quantidade": 09,
  "valor" : 5899.90 
}

### Remover pessoa (DELETE)
DELETE {{ base_url }}/api/produtos/1
Accept: */*